name: CI Build

on:
  push:
    branches-ignore:
      - main
      - master
      - release/**

  pull_request:
    branches-ignore:
      - main
      - master
      - release/**

jobs:
  build:
    uses: ./.github/workflows/job_build.yml
    with:
      solution: demo-WinApp-versioning.sln
      configuration: Debug

  coverage:
    needs: test
    uses: ./.github/workflows/job_coverage.yml
