name: CI Build

on:
  push:
    branches-ignore:
      - main
      - master
      - release/**
  pull_request:
    branches-ignore:
      - main
      - master
      - release/**

jobs:
  build:
    name: Build & Test (CI)
    uses: ./.github/workflows/job_build_test.yml
    with:
      solution: demo-WinApp-versioning.sln
      configuration: Debug