name: CI Build

on:
  push:
    branches-ignore:
      - main
      - master
      - release/**
  pull_request:
    branches-ignore:
      - main
      - master
      - release/**

permissions:
  contents: read
#  actions: read
  checks: write

jobs:
  build:
    uses: ./.github/workflows/job_build_test.yml
    with:
      solution: demo-WinApp-versioning.sln
      configuration: Debug