name: CI Build

on:
  push:
    branches-ignore:
      - main
      - master
      - release/**
  pull_request:
    branches-ignore:
      - main
      - master
      - release/**

jobs:
  build:
    name: Build & Test (CI)
    runs-on: windows-latest

    env:
      Solution_Name: demo-WinApp-versioning.sln

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required for GitVersion to work correctly

      - name: Install GitVersion 5.x
        uses: gittools/actions/gitversion/setup@v1.1.1
        with:
          versionSpec: '5.x' # Install the latest GitVersion 5.x

      - name: Calculate GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v1.1.1
        with:
          additionalArguments: '/output json /verbosity diagnostic'

      - name: Dump GitVersion outputs
        run: |
          echo "Branch: ${{ steps.gitversion.outputs.branchName }}"
          echo "FullSemVer: ${{ steps.gitversion.outputs.fullSemVer }}"
          echo "MajorMinorPatch: ${{ steps.gitversion.outputs.majorMinorPatch }}"


      - name: Setup MSBuild.exe (2022)
        uses: microsoft/setup-msbuild@v2
        with:
          vs-version: '2022'

      - name: Restore NuGet Packages
        run: nuget restore $env:Solution_Name

      - name: Build Solution
        run: msbuild $env:Solution_Name /p:Configuration=Debug

      # Optional: Run Unit Tests
      # - name: Run Unit Tests
      #   run: vstest.console.exe "Path\To\Tests.dll"

      - name: Preview GitVersion
        run: |
          echo "FullSemVer: ${{ steps.gitversion.outputs.fullSemVer }}"
          echo "Branch: ${{ steps.gitversion.outputs.branchName }}"
