name: On Pull Request Opened

on:
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    uses: ./.github/workflows/job_build_test.yml
    with:
      solution: demo-WinApp-versioning.sln
      configuration: Release