name: Release Pipeline

on:
  push:
    branches:
      - main
      - master
      - release/**

permissions:
  contents: write  # required for GitHub release

jobs:
  build:
    uses: ./.github/workflows/job_build_test.yml
    with:
      solution: demo-WinApp-versioning.sln
      configuration: Release

  # coverage:
  #   needs: test
  #   uses: ./.github/workflows/job_coverage.yml

  package:
    needs: build
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for GitVersion

      - name: Setup GitVersion
        uses: gittools/actions/gitversion/setup@v3.2.0
        with:
          versionSpec: '5.x'

      - name: Calculate GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v3.2.0
        with:
          updateAssemblyInfo: true

      - name: Display GitVersion
        run: |
          echo "GitVersion: ${{ steps.gitversion.outputs.fullSemVer }}"

      - name: Set ZIP Filename
        id: vars
        run: |
          $zipName = "demoWinApp-v${{ steps.gitversion.outputs.fullSemVer }}.zip"
          echo "zip_name=$zipName" >> $env:GITHUB_OUTPUT

      - name: Download Build Output
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: build

      - name: Zip Files
        run: |
          Compress-Archive -Path "build\*" -DestinationPath "${{ steps.vars.outputs.zip_name }}"

      - name: Upload Zip
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.vars.outputs.zip_name }}
          path: ${{ steps.vars.outputs.zip_name }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.gitversion.outputs.fullSemVer }}
          name: Release v${{ steps.gitversion.outputs.fullSemVer }}
          files: ${{ steps.vars.outputs.zip_name }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
